Repository OCA/odoo-pim, pull requests merged in 2020-06, with the labels that each got.

#9 [CHG] add dedicated product view for PIM and refactor addons structure
  .gitignore
  pim/__manifest__.py
  pim/readme/CONTRIBUTORS.rst
  pim/views/attribute_attribute.xml
  pim/views/attribute_group.xml
  pim/views/attribute_set.xml
  pim/views/pim_view.xml
  pim/views/product_view.xml
  pim_attribute_set/README.rst
  pim_attribute_set/__init__.py
  pim_attribute_set/__manifest__.py
  pim_attribute_set/readme/CONTRIBUTORS.rst
  pim_attribute_set/readme/DESCRIPTION.rst
  pim_attribute_set/readme/ROADMAP.rst
  pim_attribute_set/readme/USAGE.rst
  pim_attribute_set/static/description/index.html
  setup/pim_attribute_set/odoo/addons/pim_attribute_set
  setup/pim_attribute_set/setup.py
Labels: approved, bot is merging ⏳

#7 [12.0][ADD] add new addon attribute_set_searchable
  attribute_set_searchable/README.rst
  attribute_set_searchable/__init__.py
  attribute_set_searchable/__manifest__.py
  attribute_set_searchable/models/__init__.py
  attribute_set_searchable/models/attribute_attribute.py
  attribute_set_searchable/models/ir_ui_custom_field_filter.py
  attribute_set_searchable/readme/CONTRIBUTORS.rst
  attribute_set_searchable/readme/DESCRIPTION.rst
  attribute_set_searchable/readme/USAGE.rst
  attribute_set_searchable/tests/__init__.py
  attribute_set_searchable/tests/test_attribute_set_searchable.py
  attribute_set_searchable/views/attribute_attribute.xml
  pim/__manifest__.py
  setup/attribute_set_searchable/odoo/addons/attribute_set_searchable
  setup/attribute_set_searchable/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#11 [ADD] add new features to manage completion rate and completion state…
  attribute_set_completeness/README.rst
  attribute_set_completeness/__init__.py
  attribute_set_completeness/__manifest__.py
  attribute_set_completeness/models/__init__.py
  attribute_set_completeness/models/attribute_set.py
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/readme/CONTRIBUTORS.rst
  attribute_set_completeness/readme/DESCRIPTION.rst
  attribute_set_completeness/readme/USAGE.rst
  attribute_set_completeness/security/attribute_set_completeness.xml
  attribute_set_completeness/tests/__init__.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set.xml
  attribute_set_completeness/views/attribute_set_completeness.xml
  pim/__manifest__.py
  pim/security/pim_security.xml
  pim/views/product_view.xml
  product_attribute_set_completeness/README.rst
  product_attribute_set_completeness/__init__.py
  product_attribute_set_completeness/__manifest__.py
  product_attribute_set_completeness/readme/CONTRIBUTORS.rst
  product_attribute_set_completeness/readme/DESCRIPTION.rst
  product_attribute_set_completeness/readme/USAGE.rst
  product_attribute_set_completeness/views/product_template_view.xml
  setup/attribute_set_completeness/odoo/addons/attribute_set_completeness
  setup/attribute_set_completeness/setup.py
  setup/product_attribute_set_completeness/odoo/addons/product_attribute_set_completeness
  setup/product_attribute_set_completeness/setup.py
Labels: approved, bot is merging ⏳, needs review

#17 [10.0][BCK] product_attribute_set
  product_attribute_set/README.rst
  product_attribute_set/__init__.py
  product_attribute_set/__manifest__.py
  product_attribute_set/demo/product_attribute.xml
  product_attribute_set/models/__init__.py
  product_attribute_set/models/product.py
  product_attribute_set/models/product_category.py
  product_attribute_set/readme/CONTRIBUTORS.rst
  product_attribute_set/readme/DESCRIPTION.rst
  product_attribute_set/readme/ROADMAP.rst
  product_attribute_set/readme/USAGE.rst
  product_attribute_set/static/description/index.html
  product_attribute_set/views/product.xml
  product_attribute_set/views/product_category.xml
  setup/product_attribute_set/odoo/__init__.py
  setup/product_attribute_set/odoo/addons/__init__.py
  setup/product_attribute_set/odoo/addons/product_attribute_set
  setup/product_attribute_set/setup.py
Labels: bot is merging ⏳, migration, needs review

#19 [10.0][BCK] pim
  pim/README.rst
  pim/__init__.py
  pim/__manifest__.py
  pim/data/ir_module_category_data.xml
  pim/readme/CONFIGURE.rst
  pim/readme/CONTRIBUTORS.rst
  pim/readme/DESCRIPTION.rst
  pim/readme/ROADMAP.rst
  pim/readme/USAGE.rst
  pim/security/pim_security.xml
  pim/static/description/icon.png
  pim/static/description/index.html
  pim/views/attribute_attribute.xml
  pim/views/attribute_group.xml
  pim/views/attribute_set.xml
  pim/views/pim_view.xml
  pim/views/product_view.xml
  setup/pim/odoo/addons/pim
  setup/pim/setup.py
Labels: bot is merging ⏳, migration, needs review

#30 [FIX] required properties in fields_view_get must be linked to related attribute_set
  attribute_set/models/attribute_attribute.py
  attribute_set/tests/test_build_view.py
  attribute_set/views/attribute_set_view.xml
Labels: bot is merging ⏳

#29 [FIX] required properties in fields_view_get must be linked to related attribute_set
  attribute_set/models/attribute_attribute.py
  attribute_set/tests/test_build_view.py
  attribute_set/views/attribute_set_view.xml
Labels: bot is merging ⏳

#32 [10.0][FIX] do not replace odoo product defaut tree view by the pim view
  pim/__manifest__.py
  pim/views/pim_view.xml
  pim/views/product_view.xml
Labels: bot is merging ⏳

#33 [12.0][FIX] do not replace odoo product defaut tree view by the pim view
  pim/__manifest__.py
  pim/views/pim_view.xml
  pim/views/product_view.xml
Labels: bot is merging ⏳

#27 [10.0][BCK] attribute_set_completeness
  attribute_set_completeness/README.rst
  attribute_set_completeness/__init__.py
  attribute_set_completeness/__manifest__.py
  attribute_set_completeness/models/__init__.py
  attribute_set_completeness/models/attribute_set.py
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/readme/CONTRIBUTORS.rst
  attribute_set_completeness/readme/DESCRIPTION.rst
  attribute_set_completeness/readme/USAGE.rst
  attribute_set_completeness/security/attribute_set_completeness.xml
  attribute_set_completeness/tests/__init__.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set.xml
  attribute_set_completeness/views/attribute_set_completeness.xml
  pim/__manifest__.py
  pim/security/pim_security.xml
  pim/views/product_view.xml
  product_attribute_set_completeness/README.rst
  product_attribute_set_completeness/__init__.py
  product_attribute_set_completeness/__manifest__.py
  product_attribute_set_completeness/readme/CONTRIBUTORS.rst
  product_attribute_set_completeness/readme/DESCRIPTION.rst
  product_attribute_set_completeness/readme/USAGE.rst
  product_attribute_set_completeness/views/product_template_view.xml
  setup/attribute_set_completeness/odoo/__init__.py
  setup/attribute_set_completeness/odoo/addons/__init__.py
  setup/attribute_set_completeness/odoo/addons/attribute_set_completeness
  setup/attribute_set_completeness/setup.py
  setup/product_attribute_set_completeness/odoo/__init__.py
  setup/product_attribute_set_completeness/odoo/addons/__init__.py
  setup/product_attribute_set_completeness/odoo/addons/product_attribute_set_completeness
  setup/product_attribute_set_completeness/setup.py
Labels: bot is merging ⏳, needs review

#35 [10.0][FIX] attribute_set_completeness: Fix view
  attribute_set_completeness/views/attribute_set_completeness.xml
Labels: bot is merging ⏳, needs review

#28 [10.0][ADD] add new addon to allow searches based on a list of values
  pim/__manifest__.py
  product_search_multi_value/README.rst
  product_search_multi_value/__init__.py
  product_search_multi_value/__manifest__.py
  product_search_multi_value/data/search_field_data.xml
  product_search_multi_value/models/__init__.py
  product_search_multi_value/models/product_template.py
  product_search_multi_value/readme/CONFIGURE.rst
  product_search_multi_value/readme/CONTRIBUTORS.rst
  product_search_multi_value/readme/DESCRIPTION.rst
  product_search_multi_value/readme/ROADMAP.rst
  product_search_multi_value/readme/USAGE.rst
  product_search_multi_value/tests/__init__.py
  product_search_multi_value/tests/test_product_search_multi_value.py
  product_search_multi_value/views/product_template_view.xml
  setup/product_search_multi_value/odoo/__init__.py
  setup/product_search_multi_value/odoo/addons/__init__.py
  setup/product_search_multi_value/odoo/addons/product_search_multi_value
  setup/product_search_multi_value/setup.py
Labels: bot is merging ⏳

#40 10.0 update pre commit sbi
  .editorconfig
  .eslintrc.yml
  .flake8
  .git-blame-ignore-revs
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .travis.yml
  attribute_set/models/attribute_attribute.py
  attribute_set/models/attribute_option.py
  attribute_set/models/attribute_set_owner.py
  attribute_set/tests/test_build_view.py
  attribute_set/tests/test_custom_attribute.py
  attribute_set/wizard/attribute_option_wizard.py
  attribute_set_completeness/__init__.py
  attribute_set_completeness/models/__init__.py
  attribute_set_completeness/models/attribute_set.py
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/tests/__init__.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set_completeness.xml
  attribute_set_mass_edit/__init__.py
  attribute_set_mass_edit/models/__init__.py
  attribute_set_mass_edit/models/attribute_attribute.py
  attribute_set_mass_edit/models/attribute_group.py
  attribute_set_mass_edit/tests/__init__.py
  attribute_set_mass_edit/tests/test_attribute_set_mass_edit.py
  pim/__init__.py
  pim/models/__init__.py
  pim/tests/__init__.py
  pim/tests/test_pim_attribute_set_mass_edit.py
  product_search_multi_value/__init__.py
  product_search_multi_value/models/__init__.py
  product_search_multi_value/models/product_template.py
  product_search_multi_value/tests/__init__.py
Labels: bot is merging ⏳

#41 Update pre-commit config (pin flake8)
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#42 [13.0][PORT] 41 from 12.0
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#37 [10.0][IMP] Some improvements with completeness (see commits)
  attribute_set_completeness/models/attribute_set.py
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set.xml
  attribute_set_completeness/views/attribute_set_completeness.xml
  product_attribute_set_completeness/views/product_template_view.xml
Labels: bot is merging ⏳

#43 [10.0][FIX] attribute_set_completeness: fix search method
  attribute_set_completeness/models/attribute_set_owner_mixin.py
Labels: bot is merging ⏳

#36 [10.0][ADD] add new addon attribute_set_searchable
  attribute_set_searchable/README.rst
  attribute_set_searchable/__init__.py
  attribute_set_searchable/__manifest__.py
  attribute_set_searchable/models/__init__.py
  attribute_set_searchable/models/attribute_attribute.py
  attribute_set_searchable/models/ir_ui_custom_field_filter.py
  attribute_set_searchable/readme/CONTRIBUTORS.rst
  attribute_set_searchable/readme/DESCRIPTION.rst
  attribute_set_searchable/readme/USAGE.rst
  attribute_set_searchable/tests/__init__.py
  attribute_set_searchable/tests/test_attribute_set_searchable.py
  attribute_set_searchable/views/attribute_attribute.xml
  pim/__manifest__.py
  setup/attribute_set_searchable/odoo/__init__.py
  setup/attribute_set_searchable/odoo/addons/__init__.py
  setup/attribute_set_searchable/odoo/addons/attribute_set_searchable
  setup/attribute_set_searchable/setup.py
  test-requirements.txt
Labels: bot is merging ⏳
