Repository OCA/odoo-pim, pull requests merged in 2020-09, with the labels that each got.

#34 [13.0][FIX] do not replace odoo product defaut tree view by the pim view
  pim/__manifest__.py
  pim/views/pim_view.xml
  pim/views/product_view.xml
Labels: bot is merging ⏳

#15 [13.0][MIG] attribute_set
  attribute_set/__init__.py
  attribute_set/__manifest__.py
  attribute_set/models/attribute_attribute.py
  attribute_set/readme/CONTRIBUTORS.rst
  attribute_set/utils/__init__.py
  attribute_set/utils/orm.py
  attribute_set/views/attribute_attribute_view.xml
  attribute_set/views/attribute_option_view.xml
  attribute_set/views/attribute_set_view.xml
  setup/attribute_set/odoo/addons/attribute_set
  setup/attribute_set/setup.py
Labels: bot is merging ⏳, migration, needs review

#18 [13.0][MIG] product_attribute_set
  product_attribute_set/__manifest__.py
  product_attribute_set/models/product.py
  product_attribute_set/readme/CONTRIBUTORS.rst
  setup/product_attribute_set/odoo/addons/product_attribute_set
  setup/product_attribute_set/setup.py
Labels: bot is merging ⏳, migration, needs review

#20 [13.0][MIG] pim
  pim/__manifest__.py
  pim/readme/CONTRIBUTORS.rst
  pim/views/attribute_attribute.xml
  pim/views/attribute_group.xml
  pim/views/attribute_set.xml
  pim/views/pim_view.xml
  pim/views/product_view.xml
  setup/pim/odoo/addons/pim
  setup/pim/setup.py
Labels: bot is merging ⏳, migration, needs review

#31 [FIX] required properties in fields_view_get must be linked to related attribute_set
  attribute_set/models/attribute_attribute.py
  attribute_set/tests/test_build_view.py
  attribute_set/views/attribute_set_view.xml
Labels: bot is merging ⏳

#47 [FIX] pim: fix missing context in product action for native attributes
  pim/views/product_view.xml
Labels: bot is merging ⏳

#46 [10.0][FIX] attribute_set: Don't override base fields
  attribute_set/models/attribute_set_owner.py
Labels: bot is merging ⏳, enhancement, needs review

#45 [FIX] attribute_set_completeness: speed up completion fields
  attribute_set_completeness/__init__.py
  attribute_set_completeness/__manifest__.py
  attribute_set_completeness/components/__init__.py
  attribute_set_completeness/components/attribute_set_owner_event_listener.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/tests/res_partner_event_listener.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  product_attribute_set_completeness/__init__.py
  product_attribute_set_completeness/components/__init__.py
  product_attribute_set_completeness/components/product_template_event_listener.py
Labels: bot is merging ⏳

#38 [10.0][IMP] product_attribute_set: Set default for new products
  pim/__manifest__.py
  pim/models/__init__.py
  pim/models/res_config_settings.py
  pim/views/pim_view.xml
  pim/views/res_config_settings.xml
  product_attribute_set/models/__init__.py
  product_attribute_set/models/product.py
  product_attribute_set/models/res_company.py
Labels: bot is merging ⏳
