Repository OCA/odoo-pim, pull requests merged in 2020-10, with the labels that each got.

#48 [12.0][FWD #37] attribute_set_completeness improvements
  attribute_set_completeness/models/attribute_set.py
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set.xml
  attribute_set_completeness/views/attribute_set_completeness.xml
  product_attribute_set_completeness/views/product_template_view.xml
Labels: bot is merging ⏳, needs review

#53 [12.0][FWD] pim: fix missing context in product action for native attributes
  pim/views/product_view.xml
Labels: bot is merging ⏳

#49 [12.0][FWD] attribute_set_completeness: fix search method
  attribute_set_completeness/models/attribute_set_owner_mixin.py
Labels: bot is merging ⏳

#50 [12.0][FWD] product_attribute_set: Set default for new products
  pim/__manifest__.py
  pim/models/__init__.py
  pim/models/res_config_settings.py
  pim/views/pim_view.xml
  pim/views/res_config_settings.xml
  product_attribute_set/models/__init__.py
  product_attribute_set/models/product.py
  product_attribute_set/models/res_company.py
Labels: bot is merging ⏳

#52 [12.0][FWD] attribute_set: Don't override base fields
  attribute_set/models/attribute_set_owner.py
Labels: bot is merging ⏳

#51 [12.0][FWD] attribute_set_completeness: speed up completion fields
  attribute_set_completeness/__init__.py
  attribute_set_completeness/__manifest__.py
  attribute_set_completeness/components/__init__.py
  attribute_set_completeness/components/attribute_set_owner_event_listener.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/tests/res_partner_event_listener.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  product_attribute_set_completeness/__init__.py
  product_attribute_set_completeness/components/__init__.py
  product_attribute_set_completeness/components/product_template_event_listener.py
Labels: bot is merging ⏳

#54 [12.0][FWD] attribute_set_mass_editing: adapt to v12/13 changes
  attribute_set_mass_edit/__init__.py
  attribute_set_mass_edit/models/__init__.py
  attribute_set_mass_edit/models/attribute_attribute.py
  attribute_set_mass_edit/models/attribute_group.py
  attribute_set_mass_edit/models/mass_editing.py
  attribute_set_mass_edit/tests/test_attribute_set_mass_edit.py
  attribute_set_mass_edit/wizards/__init__.py
  attribute_set_mass_edit/wizards/mass_editing_wizard.py
  pim/models/attribute_attribute.py
  pim/tests/test_pim_attribute_set_mass_edit.py
Labels: approved, bot is merging ⏳

#56 [MIG] attribute_set_searchable: Migration to 13.0
  attribute_set_searchable/README.rst
  attribute_set_searchable/__init__.py
  attribute_set_searchable/__manifest__.py
  attribute_set_searchable/models/__init__.py
  attribute_set_searchable/models/attribute_attribute.py
  attribute_set_searchable/models/ir_ui_custom_field_filter.py
  attribute_set_searchable/readme/CONTRIBUTORS.rst
  attribute_set_searchable/readme/DESCRIPTION.rst
  attribute_set_searchable/readme/USAGE.rst
  attribute_set_searchable/static/description/index.html
  attribute_set_searchable/tests/__init__.py
  attribute_set_searchable/tests/test_attribute_set_searchable.py
  attribute_set_searchable/views/attribute_attribute.xml
  setup/attribute_set_searchable/odoo/addons/attribute_set_searchable
  setup/attribute_set_searchable/setup.py
Labels: bot is merging ⏳

#57 [MIG] attribute_set_mass_edit: Migration to 13.0
  attribute_set_mass_edit/README.rst
  attribute_set_mass_edit/__init__.py
  attribute_set_mass_edit/__manifest__.py
  attribute_set_mass_edit/models/__init__.py
  attribute_set_mass_edit/models/attribute_attribute.py
  attribute_set_mass_edit/models/attribute_group.py
  attribute_set_mass_edit/models/mass_editing.py
  attribute_set_mass_edit/readme/CONTRIBUTORS.rst
  attribute_set_mass_edit/readme/DESCRIPTION.rst
  attribute_set_mass_edit/readme/USAGE.rst
  attribute_set_mass_edit/static/description/index.html
  attribute_set_mass_edit/tests/__init__.py
  attribute_set_mass_edit/tests/test_attribute_set_mass_edit.py
  attribute_set_mass_edit/views/attribute_attribute.xml
  attribute_set_mass_edit/wizards/__init__.py
  attribute_set_mass_edit/wizards/mass_editing_wizard.py
  setup/attribute_set_mass_edit/odoo/addons/attribute_set_mass_edit
  setup/attribute_set_mass_edit/setup.py
Labels: bot is merging ⏳

#64 [12.0] improve UI on attribute_set_completeness
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set_completeness.xml
  pim/views/product_view.xml
  product_attribute_set_completeness/views/product_template_view.xml
Labels: approved, bot is merging ⏳
