Repository OCA/odoo-pim, pull requests merged in 2021-10, with the labels that each got.

#98 [14.0][MIG] attribute_set_completeness
  attribute_set_completeness/README.rst
  attribute_set_completeness/__init__.py
  attribute_set_completeness/__manifest__.py
  attribute_set_completeness/components/__init__.py
  attribute_set_completeness/components/attribute_set_owner_event_listener.py
  attribute_set_completeness/models/__init__.py
  attribute_set_completeness/models/attribute_set.py
  attribute_set_completeness/models/attribute_set_completeness.py
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  attribute_set_completeness/readme/CONTRIBUTORS.rst
  attribute_set_completeness/readme/DESCRIPTION.rst
  attribute_set_completeness/readme/USAGE.rst
  attribute_set_completeness/security/attribute_set_completeness.xml
  attribute_set_completeness/static/description/index.html
  attribute_set_completeness/tests/__init__.py
  attribute_set_completeness/tests/res_partner_event_listener.py
  attribute_set_completeness/tests/test_attribute_set_completeness.py
  attribute_set_completeness/views/attribute_set.xml
  attribute_set_completeness/views/attribute_set_completeness.xml
  setup/attribute_set_completeness/odoo/addons/attribute_set_completeness
  setup/attribute_set_completeness/setup.py
Labels: approved, bot is merging ⏳

#99 [14.0][MIG] product_attribute_set_completeness
  pim/__manifest__.py
  pim/views/product_view.xml
  product_attribute_set_completeness/README.rst
  product_attribute_set_completeness/__init__.py
  product_attribute_set_completeness/__manifest__.py
  product_attribute_set_completeness/components/__init__.py
  product_attribute_set_completeness/components/product_template_event_listener.py
  product_attribute_set_completeness/readme/CONTRIBUTORS.rst
  product_attribute_set_completeness/readme/DESCRIPTION.rst
  product_attribute_set_completeness/readme/USAGE.rst
  product_attribute_set_completeness/static/description/index.html
  product_attribute_set_completeness/views/product_template_view.xml
  setup/product_attribute_set_completeness/odoo/addons/product_attribute_set_completeness
  setup/product_attribute_set_completeness/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#74 14.0 [FIX] product category write
  product_attribute_set/models/product_category.py
Labels: bot is merging ⏳

#83 [FIX] 14.0 mass_edit several attribute in a group
  attribute_set_mass_edit/models/attribute_attribute.py
  attribute_set_mass_edit/models/attribute_group.py
  attribute_set_mass_edit/tests/test_attribute_set_mass_edit.py
Labels: enhancement, approved, bot is merging ⏳, needs review
