Repository OCA/odoo-pim, pull requests merged in 2022-10, with the labels that each got.

#108 [14.0][FIX] attribute_set_completeness
  attribute_set_completeness/__manifest__.py
  attribute_set_completeness/migrations/14.0.1.0.1/pre-migration.py
Labels: approved, ready to merge, bot is merging ⏳

#120 [15.0] [MIG] attribute_set
  attribute_set/README.rst
  attribute_set/__init__.py
  attribute_set/__manifest__.py
  attribute_set/i18n/attribute_set.pot
  attribute_set/models/__init__.py
  attribute_set/models/attribute_attribute.py
  attribute_set/models/attribute_group.py
  attribute_set/models/attribute_option.py
  attribute_set/models/attribute_set.py
  attribute_set/models/attribute_set_owner.py
  attribute_set/readme/CONTRIBUTORS.rst
  attribute_set/readme/DESCRIPTION.rst
  attribute_set/readme/ROADMAP.rst
  attribute_set/readme/USAGE.rst
  attribute_set/security/attribute_security.xml
  attribute_set/security/ir.model.access.csv
  attribute_set/static/description/icon.png
  attribute_set/static/description/index.html
  attribute_set/tests/__init__.py
  attribute_set/tests/models.py
  attribute_set/tests/test_build_view.py
  attribute_set/tests/test_custom_attribute.py
  attribute_set/utils/__init__.py
  attribute_set/utils/orm.py
  attribute_set/views/attribute_attribute_view.xml
  attribute_set/views/attribute_group_view.xml
  attribute_set/views/attribute_option_view.xml
  attribute_set/views/attribute_set_view.xml
  attribute_set/views/menu_view.xml
  attribute_set/wizard/__init__.py
  attribute_set/wizard/attribute_option_wizard.py
  attribute_set/wizard/attribute_option_wizard_view.xml
  requirements.txt
  setup/attribute_set/odoo/addons/attribute_set
  setup/attribute_set/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#110 [14.0] attribute_set_completeness: store completion state and rate for allowing searches
  attribute_set_completeness/models/attribute_set_owner_mixin.py
  product_attribute_set_completeness/views/product_template_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳, needs review

#93 [MIG][14.0] product_search_multi_value
  product_search_multi_value/README.rst
  product_search_multi_value/__init__.py
  product_search_multi_value/__manifest__.py
  product_search_multi_value/data/search_field_data.xml
  product_search_multi_value/models/__init__.py
  product_search_multi_value/models/product_template.py
  product_search_multi_value/readme/CONFIGURE.rst
  product_search_multi_value/readme/CONTRIBUTORS.rst
  product_search_multi_value/readme/DESCRIPTION.rst
  product_search_multi_value/readme/ROADMAP.rst
  product_search_multi_value/readme/USAGE.rst
  product_search_multi_value/static/description/index.html
  product_search_multi_value/tests/__init__.py
  product_search_multi_value/tests/test_product_search_multi_value.py
  product_search_multi_value/views/product_template_view.xml
  setup/product_search_multi_value/odoo/addons/product_search_multi_value
  setup/product_search_multi_value/setup.py
Labels: approved, bot is merging ⏳, migration, needs review
