Repository OCA/odoo-pim, pull requests merged in 2023-01, with the labels that each got.

#136 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  README.md
Labels: bot is merging ⏳

#107 [14.0][FIX] pim
  pim/views/product_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳, needs review

#100 [14.0][ADD]attribut_set: manage company_dependent attributes
  attribute_set/models/__init__.py
  attribute_set/models/attribute_attribute.py
  attribute_set/models/ir_model.py
  attribute_set/tests/test_custom_attribute.py
  attribute_set/views/attribute_attribute_view.xml
Labels: approved, ready to merge, bot is merging ⏳, needs review

#122 [14.0][FIX] Add "Attribute Groups" item to Technical menu
  attribute_set/views/attribute_group_view.xml
Labels: approved, bot is merging ⏳

#137 [14.0] pim: add sequence on product tree view
  pim/views/product_view.xml
Labels: approved, bot is merging ⏳

#138 [14.0][FIX] attribute_set: fix missing column
  attribute_set/__manifest__.py
  attribute_set/migrations/14.0.1.3.1/pre-migration.py
Labels: approved, bot is merging ⏳
