Repository OCA/odoo-pim, pull requests merged in 2023-05, with the labels that each got.

#125 [13.0][IMP]product_attribute_set: Improve write on category
  product_attribute_set/models/product_category.py
  product_attribute_set/tests/__init__.py
  product_attribute_set/tests/test_product_attribute_set.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#151 [14.0][FW]product attribute set: Forward Port improvements
  product_attribute_set/models/product_category.py
  product_attribute_set/tests/__init__.py
  product_attribute_set/tests/test_product_attribute_set.py
Labels: bot is merging ⏳

#135 [14.0][FIX] attribute_set: assure _instanciate_attrs doesn't break
  attribute_set/__init__.py
  attribute_set/__manifest__.py
  attribute_set/hooks.py
Labels: approved, bot is merging ⏳
